<?php

use Jwebas\Debugger\Panels\ConfigPanel;

/** @var ConfigPanel $this */

?>

<style class="tracy-debug">
    .tracy-ConfigPanel table.tracy-table .e {
        width : 100px;
    }

    .tracy-ConfigPanel table.tracy-table .v {
        max-width : 560px;
    }
</style>

<h1><?= $this->getIcon() ?> <?= $this->title ?></h1>

<div class="tracy-inner tracy-ConfigPanel">
    <div class="tracy-inner-container">
        <table class="tracy-table tracy-sortable">
            <thead>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getData() as $title => $value): ?>
                <tr>
                    <td class="e"><?= $title ?></td>
                    <td class="v"><?= $this->toHtml($value) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
