<?php declare(strict_types=1);

/** @var \Jwebas\Debugger\Support\Panel $this */
/** @var array $data */

?>

<style class="tracy-debug">
    table.tracy-table.table-slimTwig .e {
        width : 120px;
    }

    table.tracy-table.table-slimTwig .v {
        max-width : 500px;
    }
</style>

<span style="font-weight: bold;">Paths</span>

<table class="tracy-table tracy-sortable table-slimTwig">
    <thead>
    <tr>
        <th>Namespace</th>
        <th>Path</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['paths'] as $namespace => $path): ?>
        <tr>
            <td class="e"><?= $namespace ?></td>
            <td class="v"><?= $this->toHtml($path) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<span style="font-weight: bold;">Extensions</span>

<table class="tracy-table tracy-sortable table-slimTwig">
    <thead>
    <tr>
        <th>Extension</th>
        <th>Data</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['extensions'] as $title => $value): ?>
        <tr>
            <td class="e"><?= $title ?></td>
            <td class="v"><?= $this->toHtml($value) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<span style="font-weight: bold;">Twig Loader</span>
<div style="margin-bottom: 15px;"><?= $this->toHtml($data['loader']) ?></div>

<span style="font-weight: bold;">Twig</span>
<div style="margin-bottom: 15px;"><?= $this->toHtml($data['full']) ?></div>

<span style="font-weight: bold;">Twig Profile</span>
<div><?= $this->toHtml($data['twigProfile']) ?></div>
