<?php declare(strict_types=1);

/** @var \Jwebas\Debugger\Support\Panel $this */
/** @var array $data */

?>

<style class="tracy-debug">
    table.tracy-table.table-slimEnvironment .e {
        width : 130px;
    }

    table.tracy-table.table-slimEnvironment .v {
        max-width : 400px;
    }
</style>

<table class="tracy-table tracy-sortable table-slimEnvironment">
    <thead>
    <tr>
        <th>Key</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['all'] as $title => $value): ?>
        <tr>
            <td class="e"><?= $title ?></td>
            <td class="v"><?= $this->toHtml($value) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
