<?php declare(strict_types=1);

/** @var array $data */
?>

<!--suppress CssUnusedSymbol -->
<style class="tracy-debug">
    table.tracy-table.table-eloquentOrm .e {
        width : 100px;
    }

    table.tracy-table.table-eloquentOrm .v {
        width : 100px;
    }

    table.tracy-table.table-eloquentOrm .u {
        max-width : 560px;
    }
</style>

<table class="tracy-table tracy-sortable table-eloquentOrm">
    <thead>
    <tr>
        <th>No</th>
        <th>Time, ms</th>
        <th>Query / Bindings</th>
    </tr>
    </thead>
    <tbody>
    <?= $data['content'] ?>
    </tbody>
</table>
