<?php declare(strict_types=1);

use Jwebas\Debugger\Panels\Abstracts\AbstractPanel;

/** @var $this AbstractPanel */
/** @var string $panelTitle */
/** @var array $data */

?>

<style class="tracy-debug">
    .tracy-SlimRequestPanel table.tracy-table .e {
        width : 160px;
    }

    .tracy-SlimRequestPanel table.tracy-table .v {
        max-width : 500px;
    }
</style>

<h1><?= $panelTitle ?></h1>

<div class="tracy-inner tracy-SlimRequestPanel">
    <div class="tracy-inner-container">

        <table class="tracy-table tracy-sortable">
            <thead>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data['items'] as $title => $value): ?>
                <tr>
                    <td class="e"><?= $title ?></td>
                    <td class="v"><?= $this->toHtml($value) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <div><?= $this->toHtml($data['full']) ?></div>

    </div>
</div>
